package com.zinclabs.facultypro; // APNA PACKAGE NAME RAKHEIN

import androidx.activity.OnBackPressedCallback;
import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.FileProvider;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.webkit.JavascriptInterface;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.webkit.WebStorage;
import android.widget.Toast;

// --- GOOGLE SIGN IN IMPORTS ---
import com.google.android.gms.auth.api.signin.GoogleSignIn;
import com.google.android.gms.auth.api.signin.GoogleSignInAccount;
import com.google.android.gms.auth.api.signin.GoogleSignInClient;
import com.google.android.gms.auth.api.signin.GoogleSignInOptions;
import com.google.android.gms.common.api.ApiException;
import com.google.android.gms.tasks.Task;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;

import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.content.ContentValues;
import android.os.Build;
import android.os.Environment;
import android.provider.MediaStore;
import androidx.core.app.NotificationCompat;

public class MainActivity extends AppCompatActivity {

    private WebView myWebView;
    private ActivityResultLauncher<String> filePickerLauncher;

    // --- GOOGLE SIGN IN VARIABLES ---
    private GoogleSignInClient mGoogleSignInClient;
    private ActivityResultLauncher<Intent> googleSignInLauncher;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // --- STATUS BAR COLOR FIX ---
        getWindow().setStatusBarColor(android.graphics.Color.parseColor("#101622"));

        // --- CONFIGURE GOOGLE SIGN IN ---
        // Request ID Token, Email, and Profile
        GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(getString(R.string.default_web_client_id)) // Will be auto-generated by google-services
                .requestEmail()
                .build();

        mGoogleSignInClient = GoogleSignIn.getClient(this, gso);

        // --- REGISTER RESULT LAUNCHER ---
        googleSignInLauncher = registerForActivityResult(
                new ActivityResultContracts.StartActivityForResult(),
                result -> {
                    if (result.getResultCode() == RESULT_OK) {
                        Intent data = result.getData();
                        Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(data);
                        handleSignInResult(task);
                    } else {
                        // Sign in cancelled or failed
                        Toast.makeText(this, "Sign In Cancelled", Toast.LENGTH_SHORT).show();
                    }
                });

        myWebView = findViewById(R.id.myWebView);
        WebSettings webSettings = myWebView.getSettings();
        webSettings.setJavaScriptEnabled(true);
        webSettings.setDomStorageEnabled(true);
        webSettings.setAllowFileAccess(true);
        webSettings.setAllowContentAccess(true);
        webSettings.setAllowUniversalAccessFromFileURLs(true);

        // Spoof User Agent (Good Backup)
        webSettings.setUserAgentString(
                "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36");
        webSettings.setJavaScriptCanOpenWindowsAutomatically(true);

        myWebView.setWebViewClient(new WebViewClient() {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                if (url == null)
                    return false;

                // Handle WhatsApp, Tel, Mailto, etc.
                if (url.startsWith("whatsapp:") || url.startsWith("mailto:") || url.startsWith("tel:")
                        || url.startsWith("intent:")) {
                    try {
                        Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
                        startActivity(intent);
                        return true;
                    } catch (Exception e) {
                        Toast.makeText(MainActivity.this, "App not found to handle this action", Toast.LENGTH_SHORT)
                                .show();
                        return true;
                    }
                }
                return false;
            }
        });
        myWebView.setWebChromeClient(new android.webkit.WebChromeClient());

        myWebView.addJavascriptInterface(new WebAppInterface(this), "Android");

        // --- FIXED BACK GESTURE ---
        getOnBackPressedDispatcher().addCallback(this, new OnBackPressedCallback(true) {
            @Override
            public void handleOnBackPressed() {
                myWebView.evaluateJavascript("javascript:handleBackPress()", null);
            }
        });

        filePickerLauncher = registerForActivityResult(
                new ActivityResultContracts.GetContent(),
                uri -> {
                    if (uri != null) {
                        try {
                            InputStream inputStream = getContentResolver().openInputStream(uri);
                            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
                            StringBuilder stringBuilder = new StringBuilder();
                            String line;
                            while ((line = reader.readLine()) != null)
                                stringBuilder.append(line);
                            inputStream.close();
                            String jsonContent = stringBuilder.toString().replace("'", "\\'");
                            myWebView.evaluateJavascript("javascript:androidRestore('" + jsonContent + "')", null);
                        } catch (Exception e) {
                            Toast.makeText(this, "Error reading file", Toast.LENGTH_SHORT).show();
                        }
                    }
                });

        myWebView.loadUrl("file:///android_asset/index_modular.html");
    }

    // --- HANDLE SIGN IN RESULT ---
    private void handleSignInResult(Task<GoogleSignInAccount> completedTask) {
        try {
            GoogleSignInAccount account = completedTask.getResult(ApiException.class);
            String idToken = account.getIdToken();
            String email = account.getEmail();
            String name = account.getDisplayName();

            // Pass Data to JavaScript
            if (email != null) {
                // Sanitize strings
                String safeToken = idToken != null ? idToken.replace("'", "\\'") : "";
                String safeEmail = email.replace("'", "\\'");
                String safeName = name != null ? name.replace("'", "\\'") : "User";

                String jsCommand = String.format("javascript:FIREBASE_API.handleNativeLoginSuccess('%s', '%s', '%s')",
                        safeToken, safeEmail, safeName);

                myWebView.evaluateJavascript(jsCommand, null);
            }

        } catch (ApiException e) {
            android.util.Log.w("FacultyPro", "signInResult:failed code=" + e.getStatusCode());
            Toast.makeText(this, "Login Failed: " + e.getStatusCode(), Toast.LENGTH_LONG).show();
        }
    }

    public class WebAppInterface {
        Context mContext;

        WebAppInterface(Context c) {
            mContext = c;
        }

        // --- NATIVE GOOGLE LOGIN TRIGGER ---
        @JavascriptInterface
        public void nativeGoogleLogin() {
            // Must run on UI Thread to launch activity
            runOnUiThread(() -> {
                Intent signInIntent = mGoogleSignInClient.getSignInIntent();
                googleSignInLauncher.launch(signInIntent);
            });
        }

        // --- OTHER EXISTING METHODS ---
        @JavascriptInterface
        public void resetApp() {
            runOnUiThread(() -> {
                myWebView.clearCache(true);
                myWebView.clearHistory();
                WebStorage.getInstance().deleteAllData();
                Toast.makeText(mContext, "App data has been reset.", Toast.LENGTH_SHORT).show();
                myWebView.loadUrl("file:///android_asset/index_modular.html");
            });
        }

        @JavascriptInterface
        public void shareFile(String base64Content, String fileName, String mimeType) {
            try {
                File cachePath = new File(mContext.getCacheDir(), "files");
                if (!cachePath.exists())
                    cachePath.mkdirs();
                File newFile = new File(cachePath, fileName);
                FileOutputStream fos = new FileOutputStream(newFile);
                byte[] fileBytes = android.util.Base64.decode(base64Content, android.util.Base64.DEFAULT);
                fos.write(fileBytes);
                fos.close();
                Uri contentUri = FileProvider.getUriForFile(mContext, mContext.getPackageName() + ".provider", newFile);
                Intent shareIntent = new Intent(Intent.ACTION_SEND);
                shareIntent.setType(mimeType);
                shareIntent.putExtra(Intent.EXTRA_STREAM, contentUri);
                shareIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
                Intent chooser = Intent.createChooser(shareIntent, "Share via");
                chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                mContext.startActivity(chooser);
            } catch (Exception e) {
                Toast.makeText(mContext, "Error Sharing: " + e.getMessage(), Toast.LENGTH_LONG).show();
            }
        }

        @JavascriptInterface
        public void saveToDownloads(String content, String fileName, String mimeType) {
            try {
                byte[] fileBytes;
                if (mimeType.equals("application/pdf")) {
                    fileBytes = android.util.Base64.decode(content, android.util.Base64.DEFAULT);
                } else {
                    fileBytes = content.getBytes();
                }

                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                    ContentValues values = new ContentValues();
                    values.put(MediaStore.MediaColumns.DISPLAY_NAME, fileName);
                    values.put(MediaStore.MediaColumns.MIME_TYPE, mimeType);
                    values.put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS);
                    Uri uri = mContext.getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values);
                    if (uri != null) {
                        try (java.io.OutputStream out = mContext.getContentResolver().openOutputStream(uri)) {
                            out.write(fileBytes);
                        }
                        showNotification(fileName);
                        Toast.makeText(mContext, "Saved to Downloads", Toast.LENGTH_SHORT).show();
                    }
                } else {
                    File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
                    File file = new File(path, fileName);
                    FileOutputStream fos = new FileOutputStream(file);
                    fos.write(fileBytes);
                    fos.close();
                    showNotification(fileName);
                    Toast.makeText(mContext, "Saved to Downloads", Toast.LENGTH_SHORT).show();
                }
            } catch (Exception e) {
                Toast.makeText(mContext, "Download Failed: " + e.getMessage(), Toast.LENGTH_LONG).show();
            }
        }

        private void showNotification(String fileName) {
            String channelId = "download_channel";
            NotificationManager manager = (NotificationManager) mContext.getSystemService(Context.NOTIFICATION_SERVICE);
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                NotificationChannel channel = new NotificationChannel(channelId, "Downloads",
                        NotificationManager.IMPORTANCE_LOW);
                manager.createNotificationChannel(channel);
            }
            NotificationCompat.Builder builder = new NotificationCompat.Builder(mContext, channelId)
                    .setSmallIcon(android.R.drawable.stat_sys_download_done)
                    .setContentTitle("Download Complete")
                    .setContentText(fileName + " has been saved.")
                    .setPriority(NotificationCompat.PRIORITY_LOW)
                    .setAutoCancel(true);
            manager.notify((int) System.currentTimeMillis(), builder.build());
        }

        @JavascriptInterface
        public void openFilePicker() {
            filePickerLauncher.launch("application/json");
        }

        // --- CLIPBOARD METHODS FOR MAGIC TOKENS ---
        @JavascriptInterface
        public void copyToClipboard(String text) {
            runOnUiThread(() -> {
                android.content.ClipboardManager clipboard = (android.content.ClipboardManager) mContext
                        .getSystemService(Context.CLIPBOARD_SERVICE);
                android.content.ClipData clip = android.content.ClipData.newPlainText("FacultyPro Token", text);
                clipboard.setPrimaryClip(clip);
                Toast.makeText(mContext, "Copied to clipboard", Toast.LENGTH_SHORT).show();
            });
        }

        @JavascriptInterface
        public String readClipboard() {
            android.content.ClipboardManager clipboard = (android.content.ClipboardManager) mContext
                    .getSystemService(Context.CLIPBOARD_SERVICE);
            if (clipboard.hasPrimaryClip() && clipboard.getPrimaryClip().getItemCount() > 0) {
                CharSequence text = clipboard.getPrimaryClip().getItemAt(0).getText();
                return text != null ? text.toString() : "";
            }
            return "";
        }

        @JavascriptInterface
        public void exitApp() {
            finish();
        }
    }
}